{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoException\/unknownError"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknownError","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoException"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Case","modules":[{"name":"TSCoreSDK"}],"symbolKind":"case","role":"symbol","externalID":"s:9TSCoreSDK17TSCryptoExceptionO12unknownErroryA2CmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"title":"TSCryptoException.unknownError"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/tscryptoexception\/unknownerror"]}],"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoException":{"kind":"symbol","title":"TSCryptoException","url":"\/documentation\/tscoresdk\/tscryptoexception","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSCryptoException"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSCryptoException"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoException/unknownError":{"kind":"symbol","abstract":[],"role":"symbol","title":"TSCryptoException.unknownError","url":"\/documentation\/tscoresdk\/tscryptoexception\/unknownerror","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoException\/unknownError"}}}